version: '3'

services:
  mysql-db:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=shopping_societies
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=test123
    ports:
      - 3306:3306
    volumes:
      - /data/mysql
  shopping-societies-app:
    image: shopping-societies
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    ports:
      - 8888:8080
    volumes:
      - /data/shopping-societies-app
